specVersion: 1.0.0
indexerHints:
  prune: auto
schema:
  file: ./schema.graphql
dataSources:
  - kind: ethereum
    name: Referee
    network: arbitrum-one
    source:
      address: "0xfD41041180571C5D371BEA3D9550E55653671198"
      abi: Referee
      startBlock: 157193676
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - AdminChanged
        - BeaconUpgraded
        - Upgraded
      abis:
        - name: Referee
          file: ./abis/Referee.json
      eventHandlers:
        - event: AdminChanged(address,address)
          handler: handleAdminChanged
        - event: BeaconUpgraded(indexed address)
          handler: handleBeaconUpgraded
        - event: Upgraded(indexed address)
          handler: handleUpgraded
      file: ./src/referee.ts
