sources:
  - name: sentry
    handler:
      graphql:
        endpoint: https://subgraph.satsuma-prod.com/d346413f9bc1/cryptits-team--300223/xai-sentry/version/v0.0.1-new-version/api
    transforms:
      - autoPagination:
          # You might want to disable schema validation for faster startup
          validateSchema: true