sources:
  - name: sentry
    handler:
      graphql:
        endpoint: https://subgraph.satsuma-prod.com/d346413f9bc1/cryptits-team--300223/sepolia-version/version/0.0.13-sepolia/api
    transforms:
      - autoPagination:
          # You might want to disable schema validation for faster startup
          validateSchema: true