specVersion: 1.0.0
indexerHints:
  prune: auto
schema:
  file: ./schema.graphql
dataSources:
  - kind: ethereum
    name: GasSubsidy
    network: arbitrum-one
    source:
      address: "0x94F4aBC83eae00b693286B6eDCa09e1D76183C97"
      abi: GasSubsidy
      startBlock: 157193649
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - GasSubsidyRoleAdminChangedEvent
        - GasSubsidyRoleGrantedEvent
        - GasSubsidyRoleRevokedEvent
      abis:
        - name: GasSubsidy
          file: ./abis/GasSubsidy.json
      eventHandlers:
        - event: RoleAdminChanged(indexed bytes32,indexed bytes32,indexed bytes32)
          handler: handleRoleAdminChanged
        - event: RoleGranted(indexed bytes32,indexed address,indexed address)
          handler: handleRoleGranted
        - event: RoleRevoked(indexed bytes32,indexed address,indexed address)
          handler: handleRoleRevoked
      file: ./src/gas-subsidy.ts
  - kind: ethereum
    name: Xai
    network: arbitrum-one
    source:
      address: "0x4Cb9a7AE498CEDcBb5EAe9f25736aE7d428C9D66"
      abi: Xai
      startBlock: 157193610
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - XaiApprovalEvent
        - XaiConvertedToEsXaiEvent
        - XaiEsXaiAddressSetEvent
        - XaiInitializedEvent
        - XaiRoleAdminChangedEvent
        - XaiRoleGrantedEvent
        - XaiRoleRevokedEvent
        - XaiTransferEvent
      abis:
        - name: Xai
          file: ./abis/Xai.json
      eventHandlers:
        - event: Approval(indexed address,indexed address,uint256)
          handler: handleXaiApproval
        - event: ConvertedToEsXai(indexed address,uint256)
          handler: handleXaiConvertedToEsXai
        - event: EsXaiAddressSet(indexed address)
          handler: handleXaiEsXaiAddressSet
        - event: Initialized(uint8)
          handler: handleXaiInitialized
        - event: RoleAdminChanged(indexed bytes32,indexed bytes32,indexed bytes32)
          handler: handleXaiRoleAdminChanged
        - event: RoleGranted(indexed bytes32,indexed address,indexed address)
          handler: handleXaiRoleGranted
        - event: RoleRevoked(indexed bytes32,indexed address,indexed address)
          handler: handleXaiRoleRevoked
        - event: Transfer(indexed address,indexed address,uint256)
          handler: handleXaiTransfer
      file: ./src/xai.ts
  - kind: ethereum
    name: EsXai
    network: arbitrum-one
    source:
      address: "0x4C749d097832DE2FEcc989ce18fDc5f1BD76700c"
      abi: EsXai
      startBlock: 157193630
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - EsXaiApprovalEvent
        - EsXaiFoundationBasepointsUpdatedEvent
        - EsXaiInitializedEvent
        - EsXaiRedemptionCancelledEvent
        - EsXaiRedemptionCompletedEvent
        - EsXaiRedemptionStartedEvent
        - EsXaiRedemptionStatusChangedEvent
        - EsXaiRoleAdminChangedEvent
        - EsXaiRoleGrantedEvent
        - EsXaiRoleRevokedEvent
        - EsXaiTransferEvent
        - EsXaiWhitelistUpdatedEvent
        - EsXaiXaiAddressChangedEvent
      abis:
        - name: EsXai
          file: ./abis/EsXai.json
      eventHandlers:
        - event: Approval(indexed address,indexed address,uint256)
          handler: handleApproval
        - event: FoundationBasepointsUpdated(uint256)
          handler: handleFoundationBasepointsUpdated
        - event: Initialized(uint8)
          handler: handleInitialized
        - event: RedemptionCancelled(indexed address,indexed uint256)
          handler: handleRedemptionCancelled
        - event: RedemptionCompleted(indexed address,indexed uint256)
          handler: handleRedemptionCompleted
        - event: RedemptionStarted(indexed address,indexed uint256)
          handler: handleRedemptionStarted
        - event: RedemptionStatusChanged(bool)
          handler: handleRedemptionStatusChanged
        - event: RoleAdminChanged(indexed bytes32,indexed bytes32,indexed bytes32)
          handler: handleRoleAdminChanged
        - event: RoleGranted(indexed bytes32,indexed address,indexed address)
          handler: handleRoleGranted
        - event: RoleRevoked(indexed bytes32,indexed address,indexed address)
          handler: handleRoleRevoked
        - event: Transfer(indexed address,indexed address,uint256)
          handler: handleTransfer
        - event: WhitelistUpdated(address,bool)
          handler: handleWhitelistUpdated
        - event: XaiAddressChanged(indexed address)
          handler: handleXaiAddressChanged
      file: ./src/es-xai.ts
  - kind: ethereum
    name: Referee
    network: arbitrum-one
    source:
      address: "0xfD41041180571C5D371BEA3D9550E55653671198"
      abi: Referee
      startBlock: 157193676
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - RefereeRefereeApprovalEvent
        - RefereeAssertionCheckingToggledEvent
        - RefereeAssertionSubmittedEvent
        - RefereeChallengeClosedEvent
        - RefereeChallengeExpiredEvent
        - RefereeChallengeSubmittedEvent
        - RefereeChallengerPublicKeyChangedEvent
        - RefereeInitializedEvent
        - RefereeInvalidSubmissionEvent
        - RefereeKycStatusChangedEvent
        - RefereeNodeLicenseAddressChangedEvent
        - RefereeRewardsClaimedEvent
        - RefereeRoleAdminChangedEvent
        - RefereeRoleGrantedEvent
        - RefereeRoleRevokedEvent
        - RefereeRollupAddressChangedEvent
        - RefereeStakedV1Event
        - RefereeStakingEnabledEvent
        - RefereeUnstakeV1Event
        - RefereeUpdateMaxStakeAmountEvent
        - Submission
        - Challenge
      abis:
        - name: Referee
          file: ./abis/Referee.json
      eventHandlers:
        - event: Approval(indexed address,indexed address,bool)
          handler: handleApproval
        - event: AssertionCheckingToggled(bool)
          handler: handleAssertionCheckingToggled
        - event: AssertionSubmitted(indexed uint256,indexed uint256)
          handler: handleAssertionSubmitted
        - event: ChallengeClosed(indexed uint256)
          handler: handleChallengeClosed
        - event: ChallengeExpired(indexed uint256)
          handler: handleChallengeExpired
        - event: ChallengeSubmitted(indexed uint256)
          handler: handleChallengeSubmitted
        - event: ChallengerPublicKeyChanged(bytes)
          handler: handleChallengerPublicKeyChanged
        - event: Initialized(uint8)
          handler: handleInitialized
        - event: InvalidSubmission(indexed uint256,uint256)
          handler: handleInvalidSubmission
        - event: KycStatusChanged(indexed address,bool)
          handler: handleKycStatusChanged
        - event: NodeLicenseAddressChanged(address)
          handler: handleNodeLicenseAddressChanged
        - event: RewardsClaimed(indexed uint256,uint256)
          handler: handleRewardsClaimed
        - event: RoleAdminChanged(indexed bytes32,indexed bytes32,indexed bytes32)
          handler: handleRoleAdminChanged
        - event: RoleGranted(indexed bytes32,indexed address,indexed address)
          handler: handleRoleGranted
        - event: RoleRevoked(indexed bytes32,indexed address,indexed address)
          handler: handleRoleRevoked
        - event: RollupAddressChanged(address)
          handler: handleRollupAddressChanged
        - event: StakedV1(indexed address,uint256,uint256)
          handler: handleStakedV1
        - event: StakingEnabled()
          handler: handleStakingEnabled
        - event: UnstakeV1(indexed address,uint256,uint256)
          handler: handleUnstakeV1
        - event: UpdateMaxStakeAmount(uint256,uint256)
          handler: handleUpdateMaxStakeAmount
      file: ./src/referee.ts
  - kind: ethereum
    name: NodeLicense
    network: arbitrum-one
    source:
      address: "0xbc14d8563b248B79689ECbc43bBa53290e0b6b66"
      abi: NodeLicense
      startBlock: 157193743
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - NodeLicenseApprovalEvent
        - NodeLicenseApprovalForAllEvent
        - NodeLicenseClaimableChangedEvent
        - NodeLicenseFundsReceiverChangedEvent
        - NodeLicenseFundsWithdrawnEvent
        - NodeLicenseInitializedEvent
        - NodeLicensePricingTierSetOrAddedEvent
        - NodeLicensePromoCodeCreatedEvent
        - NodeLicensePromoCodeRemovedEvent
        - NodeLicenseReferralRewardEvent
        - NodeLicenseReferralRewardPercentagesChangedEvent
        - NodeLicenseRefundOccurredEvent
        - NodeLicenseRewardClaimedEvent
        - NodeLicenseRoleAdminChangedEvent
        - NodeLicenseRoleGrantedEvent
        - NodeLicenseRoleRevokedEvent
        - NodeLicenseTransferEvent
        - NodeLicenseWhitelistAmountRedeemedEvent
        - NodeLicenseWhitelistAmountUpdatedByAdminEvent
        - SentryKey
      abis:
        - name: NodeLicense
          file: ./abis/NodeLicense.json
      eventHandlers:
        - event: Approval(indexed address,indexed address,indexed uint256)
          handler: handleApproval
        - event: ApprovalForAll(indexed address,indexed address,bool)
          handler: handleApprovalForAll
        - event: ClaimableChanged(indexed address,bool)
          handler: handleClaimableChanged
        - event: FundsReceiverChanged(indexed address,address)
          handler: handleFundsReceiverChanged
        - event: FundsWithdrawn(indexed address,uint256)
          handler: handleFundsWithdrawn
        - event: Initialized(uint8)
          handler: handleInitialized
        - event: PricingTierSetOrAdded(uint256,uint256,uint256)
          handler: handlePricingTierSetOrAdded
        - event: PromoCodeCreated(string,address)
          handler: handlePromoCodeCreated
        - event: PromoCodeRemoved(string)
          handler: handlePromoCodeRemoved
        - event: ReferralReward(indexed address,indexed address,uint256)
          handler: handleReferralReward
        - event: ReferralRewardPercentagesChanged(uint256,uint256)
          handler: handleReferralRewardPercentagesChanged
        - event: RefundOccurred(indexed address,uint256)
          handler: handleRefundOccurred
        - event: RewardClaimed(indexed address,uint256)
          handler: handleRewardClaimed
        - event: RoleAdminChanged(indexed bytes32,indexed bytes32,indexed bytes32)
          handler: handleRoleAdminChanged
        - event: RoleGranted(indexed bytes32,indexed address,indexed address)
          handler: handleRoleGranted
        - event: RoleRevoked(indexed bytes32,indexed address,indexed address)
          handler: handleRoleRevoked
        - event: Transfer(indexed address,indexed address,indexed uint256)
          handler: handleTransfer
        - event: WhitelistAmountRedeemed(indexed address,uint16)
          handler: handleWhitelistAmountRedeemed
        - event: WhitelistAmountUpdatedByAdmin(indexed address,uint16)
          handler: handleWhitelistAmountUpdatedByAdmin
      file: ./src/node-license.ts
  - kind: ethereum
    name: PoolFactory
    network: arbitrum-one
    source:
      address: "0xF9E08660223E2dbb1c0b28c82942aB6B5E38b8E5"
      abi: PoolFactory
      startBlock: 200013500
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - UnstakeKeysEvent
        - StakeKeysEvent
      abis:
        - name: PoolFactory
          file: ./abis/PoolFactory.json
      eventHandlers:
        - event: StakeKeys(indexed address,indexed address,uint256,uint256,uint256)
          handler: handleStakeKeys
        - event: UnstakeKeys(indexed address,indexed address,uint256,uint256,uint256)
          handler: handleUnstakeKeys
      callHandlers:
        - function: stakeKeys(address,uint256[])
          handler: handleStakeKeysCall
      file: ./src/pool-factory.ts