name: Codecov

on: [push, pull_request]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.15.0'
          
      - name: Install pnpm
        run: npm i -g nx pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Generate coverage report
        run: nx coverage-report

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage
          slug: xai-foundation/sentry
