name: on-pr-review

on:
  pull_request:
    types: [review_requested]
    branches:
      - "*"

jobs:
  build:
    runs-on: self-hosted

    steps:
      # Step 1: Checkout the code from the PR branch
      - name: Checkout the PR branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      # Step 2: Set up environment variables for container names
      - name: Set container names
        run: |
          echo "WEB_CONNECT_CONTAINER_NAME=web-connect-${{ github.event.pull_request.number }}" >> $GITHUB_ENV
          echo "WEB_STAKING_CONTAINER_NAME=web-staking-${{ github.event.pull_request.number }}" >> $GITHUB_ENV


      - name: Check if containers exist and remove them
        run: |
          # Check if the web-connect container exists, and remove it if it does
          if [ "$(docker ps -a -q -f name=${{ env.WEB_CONNECT_CONTAINER_NAME }})" ]; then
            docker stop ${{ env.WEB_CONNECT_CONTAINER_NAME }} || true
            docker rm ${{ env.WEB_CONNECT_CONTAINER_NAME }} || true
          fi

          # Check if the web-staking container exists, and remove it if it does
          if [ "$(docker ps -a -q -f name=${{ env.WEB_STAKING_CONTAINER_NAME }})" ]; then
            docker stop ${{ env.WEB_STAKING_CONTAINER_NAME }} || true
            docker rm ${{ env.WEB_STAKING_CONTAINER_NAME }} || true
          fi

      # Step 3: Build web-connect and web-staking services using docker compose
      - name: Build Docker services
        run: |
          cd .dev-deploy
          pwd
          ls -al
          docker compose build

      # Step 4: Spin up containers with dynamic environment variables
      - name: Run Docker containers for PR review
        run: |
          pwd
          cd .dev-deploy
          pwd
          ls -al
          docker compose up -d \
            --build \
            -e MONGODB_URL=${{ secrets.MONGODB_URL }} \
            -e NEXT_PUBLIC_APP_ENV=development \
            -e WEB_CONNECT_CONTAINER_NAME=${{ env.WEB_CONNECT_CONTAINER_NAME }} \
            -e WEB_STAKING_CONTAINER_NAME=${{ env.WEB_STAKING_CONTAINER_NAME }}
